// ... (outras importações)

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';

export const LOAD_POKE_REQUEST = 'LOAD_POKE_REQUEST';
export const LOAD_POKE_SUCCESS = 'LOAD_POKE_SUCCESS';
export const LOAD_POKE_FAILURE = 'LOAD_POKE_FAILURE';

export const LOAD_TYPE_REQUEST = 'LOAD_TYPE_REQUEST';
export const LOAD_TYPE_SUCCESS = 'LOAD_TYPE_SUCCESS';
export const LOAD_TYPE_FAILURE = 'LOAD_TYPE_FAILURE';

export const LOAD_TYPE_LIST_REQUEST = 'LOAD_TYPE_LIST_REQUEST';
export const LOAD_TYPE_LIST_SUCCESS = 'LOAD_TYPE_LIST_SUCCESS';
export const LOAD_TYPE_LIST_FAILURE = 'LOAD_TYPE_LIST_FAILURE';

// ... (outras exportações)
